#pragma once

enum EntityID
{
	ID_TEX_SIMON = 1,
	ID_TEX_MAINMENU = 2,
	ID_TEX_GAMEPLAYSCREEN = 3,
	ID_TEX_WHIP = 4,
	ID_TEX_BURNBARREL = 5,
	ID_TEX_BBOX = 6,
	ID_TEX_HEART = 7,
	ID_TEX_EFFECT = 8,
	ID_TEX_WEAPON_REWARD = 9,
	ID_TEX_KATANA = 10,
	ID_TEX_MIRACULOUS_BAG = 11,
	ID_TEX_BRICK = 12,
	ID_TEX_FLOOR = 13,
	ID_TEX_ENTRANCE = 14,
	ID_TEX_KATANA_WEAPON = 15,
};