#pragma once

enum EntityID
{
	ID_TEX_SIMON = 0,
	ID_TEX_MAINMENU = 1,
	ID_TEX_GAMEPLAYSCREEN = 2,
	ID_TEX_WHIP = 3,
	ID_TEX_BURNBARREL = 4,
	ID_TEX_BBOX = 5,
	ID_TEX_HEART = 6,
	ID_TEX_EFFECT = 7,
	ID_TEX_WEAPON_REWARD = 8,
	ID_TEX_KATANA = 9,
	ID_TEX_MIRACULOUS_BAG = 10,
	ID_TEX_BRICK = 11,
};